// Well-known hospitals in Ahmedabad, offered as suggestions on the hospital form.
export const AHMEDABAD_HOSPITALS = [
  "Civil Hospital Ahmedabad (Asarwa)",
  "Sardar Vallabhbhai Patel Institute of Medical Sciences (SVP Hospital)",
  "U. N. Mehta Institute of Cardiology and Research Centre",
  "Gujarat Cancer & Research Institute",
  "Institute of Kidney Diseases and Research Centre (IKDRC)",
  "B. J. Medical College Hospital",
  "Sterling Hospital, Memnagar",
  "Apollo Hospitals International, Bhat",
  "CIMS Hospital, Science City Road",
  "Zydus Hospital, S. G. Highway",
  "HCG Hospital, Mithakhali",
  "Shalby Hospital, S. G. Highway",
  "KD Hospital, Vaishnodevi Circle",
  "Narayana Multispeciality Hospital, Rakhial",
  "Rajasthan Hospital, Shahibaug",
  "SAL Hospital, Drive-In Road",
  "Wockhardt Hospital, Mithakhali",
  "Bodyline Hospital, Ellisbridge",
  "Sanjivani Super Speciality Hospital, Ambawadi",
  "Krishna Shalby Hospital, Ghodasar",
  "Nidhi Hospital, Navrangpura",
  "Sunshine Global Hospital, Manekbaug",
  "Aastha Hospital, Naranpura",
  "Global Hospital, Paldi",
  "Lifecare Institute of Medical Science, Ellisbridge",
  "Kaizen Hospital, Ellisbridge",
  "Epic Multispeciality Hospital, Chandkheda",
  "Shreeji Hospital, Maninagar",
  "Aarogyam Hospital, Nikol",
  "Divine Multispeciality Hospital, Vastral",
] as const;
